# Generated by Django 3.2.6 on 2021-08-10 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TryModel',
            new_name='PreRegistration',
        ),
    ]
